#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD socket server
# Description:       Starts and stops the AESD socket server on port 9000
### END INIT INFO

DAEMON_NAME="aesdsocket"
DAEMON_PATH="/usr/bin/aesdsocket"
DAEMON_OPTS="-d"
PIDFILE="/var/run/aesdsocket.pid"

# Exit if the package is not installed
[ -x "$DAEMON_PATH" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$DAEMON_NAME ] && . /etc/default/$DAEMON_NAME

case "$1" in
    start)
        echo -n "Starting $DAEMON_NAME: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON_PATH --background --make-pidfile -- $DAEMON_OPTS
        if [ $? -eq 0 ]; then
            echo "OK"
        else
            echo "FAILED"
            exit 1
        fi
        ;;
    
    stop)
        echo -n "Stopping $DAEMON_NAME: "
        start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry=TERM/30/KILL/5
        if [ $? -eq 0 ]; then
            rm -f $PIDFILE
            echo "OK"
        else
            echo "FAILED"
            exit 1
        fi
        ;;
    
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    
    status)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE 2>/dev/null)
            if [ -n "$PID" ] && kill -0 $PID 2>/dev/null; then
                echo "$DAEMON_NAME is running with PID $PID"
                exit 0
            else
                echo "$DAEMON_NAME is not running (stale PID file)"
                exit 1
            fi
        else
            echo "$DAEMON_NAME is not running"
            exit 3
        fi
        ;;
    
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
