#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: AESD Socket Daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid

start() {
    echo "Starting aesdsocket..."
    start-stop-daemon --start --background \
        --make-pidfile --pidfile $PIDFILE \
        --exec $DAEMON -- -d
}

stop() {
    echo "Stopping aesdsocket..."
    start-stop-daemon --stop \
        --pidfile $PIDFILE \
        --signal SIGTERM \
        --retry 5
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

